name: TableOfContents

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install TOC updater
      run: npm install --save-prod --global-style markdown-toc
    - name: list files
      run: pwd && find .
    - name: Update table of contents
      run: markdown-toc -i recipe-book.md
