name: TableOfContents

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: list files
      run: ls -al
    - name: Update table of contents
      run: markdown-toc -i recipe-book.md
