name: TableOfContents

on: [push]

jobs:
  fix-toc:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install TOC updater
      run: npm install --save-prod --global-style markdown-toc
    
    - name: list files
      run: pwd && find . && ls -l ./node_modules/.bin/
    
    - name: Update table of contents
      run: ./node_modules/.bin/markdown-toc -i recipe-book.md

   - name: Commit to repository
     env:
       GITHUB_TOKEN: ${{ secrets.github_token }}
       COMMIT_MSG: |
         updated TOC
         skip-checks: true
     run: |
       # Hard-code user configuration
       git config user.email "actions@github.com"
       git config user.name "GitHub Actions
       # Update origin with token
       git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
       # Checkout the branch so we can push back to it
       git checkout master
       git add recipe-book.md
       # Only commit and push if we have changes
       git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push origin master)

#    - name: commit updated TOC
#      run: |
#        git config --local user.email "action@github.com"
#        git config --local user.name "GitHub Action"
#        git commit recipe-book.md -m 'updated toc in github action'

#    - name: Push changes
#      uses: ad-m/github-push-action@master
#      with:
#        github_token: ${{ secrets.GITHUB_TOKEN }}
