name: TableOfContents

on: [push]

jobs:
  fix-toc:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install TOC updater
      run: npm install --save-prod --global-style markdown-toc

    - name: Update table of contents
      run: ./node_modules/.bin/markdown-toc -i recipe-book.md

    - name: Commit to repository
      env:
        GITHUB_TOKEN: ${{ secrets.github_token }}  
        COMMIT_MSG: |
          updated TOC
          skip-checks: true
      run: |
        # Hard-code user configuration
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
        # Update origin with token
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        # Checkout the branch so we can push back to it
        git checkout ${GITHUB_REF##*/}
        git add recipe-book.md
        # Only commit and push if we have changes
        git diff --quiet && git diff --staged --quiet || (git commit -m "${COMMIT_MSG}"; git push origin ${GITHUB_REF##*/})

