name: TableOfContents

on: [push]

jobs:
  fix-toc:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install TOC updater
      run: npm install --save-prod --global-style markdown-toc
    
    - name: list files
      run: pwd && find . && ls -l ./node_modules/.bin/
    
    - name: Update table of contents
      run: ./node_modules/.bin/markdown-toc -i recipe-book.md

    - name: commit updated TOC
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Add changes" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
